### ISSUE TITLE
Threads blocking issue for 0.8.0.M8

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [r2dbc/r2dbc-postgresql#131]
0.8.0.M8 has critical thread blocking issue:

![image](https://user-images.githubusercontent.com/10498901/63157372-79b5fd80-c01f-11e9-85fd-5ab347c0761e.png)

Thread dump:

```
"reactor-tcp-nio-1" #36 daemon prio=5 os_prio=0 cpu=2453.13ms elapsed=18.73s tid=0x000001aae3d22800 nid=0x141c runnable  [0x0000007188efa000]
   java.lang.Thread.State: RUNNABLE
        at java.text.Collator.compare(java.base@11.0.3/Collator.java:305)
        at java.util.TreeMap.put(java.base@11.0.3/TreeMap.java:550)
        at io.r2dbc.postgresql.PostgresqlRowMetadata.getNameKeyedColumnMetadatas(PostgresqlRowMetadata.java:151)
        at io.r2dbc.postgresql.PostgresqlRowMetadata.<init>(PostgresqlRowMetadata.java:47)
        at io.r2dbc.postgresql.PostgresqlRowMetadata.toRowMetadata(PostgresqlRowMetadata.java:108)
        at io.r2dbc.postgresql.PostgresqlResult.lambda$toResult$1(PostgresqlResult.java:101)
        at io.r2dbc.postgresql.PostgresqlResult$$Lambda$1242/0x0000000800830c40.apply(Unknown Source)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
        at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:457)
        at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
        at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
        at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
        at reactor.core.publisher.Mono.subscribe(Mono.java:3694)
        at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:112)
        at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onComplete(FluxRepeatPredicate.java:93)
        at com.filichkin.reactor.lifter.MdcContextLifter.onComplete(MdcContextLifter.java:40)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
        at com.filichkin.reactor.lifter.MdcContextLifter.onComplete(MdcContextLifter.java:40)
        at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1594)
        at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:1842)
        at reactor.core.publisher.FluxZip$ZipInner.request(FluxZip.java:940)
        at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:799)
        at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:735)
        at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:107)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
        at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:422)
        at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:264)
        at reactor.core.publisher.FluxHide$HideSubscriber.onNext(FluxHide.java:74)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:180)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:636)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:714)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:756)
        at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:248)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:636)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:714)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:756)
        at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:248)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:113)
        at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:320)
        at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:320)
        at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:320)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:826)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:275)
        at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:849)
        at com.filichkin.reactor.lifter.MdcContextLifter.onNext(MdcContextLifter.java:28)
        at reactor.core.publisher.FluxGenerate$GenerateSubscription.next(FluxGenerate.java:169)
        at io.r2dbc.postgresql.message.backend.BackendMessageDecoder.lambda$decode$1(BackendMessageDecoder.java:100)
        at io.r2dbc.postgresql.message.backend.BackendMessageDecoder$$Lambda$455/0x000000080059d840.apply(Unknown Source)
        at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:262)
        at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:204)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1878)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1752)
        at com.filichkin.reactor.lifter.MdcContextLifter.onSubscribe(MdcContextLifter.java:22)
        at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
        at reactor.core.publisher.FluxLiftFuseable.subscribe(FluxLiftFuseable.java:70)
        at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:442)
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:244)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:205)
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:321)
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:319)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:141)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
```

**For 1.0.0.M7 everything looks fine:**

![image](https://user-images.githubusercontent.com/10498901/63157430-9d794380-c01f-11e9-8dd3-64b1bf95b9cd.png)

The problem with getNameKeyedColumnMetadatas in PostgresqlRowMetadata.java

```
private Map<String, PostgresqlColumnMetadata> getNameKeyedColumnMetadatas(List<PostgresqlColumnMetadata> columnMetadatas) {
        Map<String, PostgresqlColumnMetadata> nameKeyedColumnMetadatas = new TreeMap<>(Collator.DEFAULT);

        for (PostgresqlColumnMetadata columnMetadata : columnMetadatas) {
            nameKeyedColumnMetadatas.put(columnMetadata.getName(), columnMetadata);
        }

        return nameKeyedColumnMetadatas;
    }
```
TreeMap uses Collator singleton instance. Collator has synchronized compare method:
` public synchronized int compare(String source, String target)`

Do we need singleton instance for the Collator?

Looks like we shouldn't reuse Collator instance, just create a new one.

**Comment by mp911de** [comment]
Care to paste the stack trace as text. The image is non-readable.

**Comment by Aleksandr-Filichkin** [comment]
@mp911de  Stack trace was added

**Comment by mp911de** [comment]
From the impl doc of `RuleBasedCollator`:

> compare() and getCollationKey() are synchronized to ensure thread safety with this scheme.

It makes sense to go away from `RuleBasedCollator` and implement case-insensitive matching directly via `String.equalsIgnoreCase` to prevent synchronization issues. Creating multiple `RuleBasedCollator` isn't efficient.

**Comment by mp911de** [comment]
We have a similar issue in R2DBC SQL Server. Here's the fixing commit: https://github.com/r2dbc/r2dbc-mssql/commit/7297c9be4b1136947a03bc1b23dccfaebabfd620

Care to submit a pull request?

**Comment by Aleksandr-Filichkin** [comment]
I will submit a PR

**Comment by Aleksandr-Filichkin** [comment]
@mp911de MR is https://github.com/r2dbc/r2dbc-postgresql/pull/132

But build was failed because PostgresqlConnection doesn't implement new methods from Connection class("validate",setAutoCommit,etc)

@mp911de  Do we have a ticket for implementing new methods for PostgresqlConnection?

**Comment by killaitis** [comment]
#140 will fix the missing new methods.
