### ISSUE TITLE
Issue with dependencies in RC2

### ISSUE THREAD

**Issue by otcyury** [r2dbc/r2dbc-postgresql#188]
I started using below dependencies and what was working started throws exceptions. Is this a problem with reactor or r2dbc library? Thanks

        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-postgresql</artifactId>
            <version>0.8.0.RC2</version>
        </dependency>

		<dependency>
		    <groupId>io.r2dbc</groupId>
		    <artifactId>r2dbc-spi</artifactId>
		    <version>0.8.0.M8</version>
		</dependency>

java.lang.NoSuchMethodError: io.r2dbc.spi.Row.get(ILjava/lang/Class;)Ljava/lang/Object;
	at io.r2dbc.postgresql.PostgresqlConnectionFactory.lambda$null$14(PostgresqlConnectionFactory.java:189) ~[r2dbc-postgresql-0.8.0.RC2.jar:0.8.0.RC2]
	at io.r2dbc.postgresql.PostgresqlResult.lambda$map$2(PostgresqlResult.java:96) ~[r2dbc-postgresql-0.8.0.RC2.jar:0.8.0.RC2]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]

**Comment by skroll** [comment]
You are using 0.8.0.M8 of r2dbc-spi, but the actual dependency that r2dbc-postgresql depends on is 0.8.0.RC2. I think you just need to update your r2dbc-spi dependency to the same version.

**Comment by otcyury** [comment]
Same issue with below.

        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-postgresql</artifactId>
            <version>0.8.0.RC2</version>
        </dependency>

		<dependency>
		    <groupId>io.r2dbc</groupId>
		    <artifactId>r2dbc-spi</artifactId>
		    <version>0.8.0.RC2</version>
		</dependency>

**Comment by skroll** [comment]
I just built the project myself, and integration tests passed. The "NoSuchMethodError" you are getting says that: `io.r2dbc.spi.Row.get(ILjava/lang/Class;)Ljava/lang/Object` does not exist, but I clearly see this in the compiled classes for r2dbc-spi:
```
public interface Row {
  // ...
  @Nullable
  <T> T get(int var1, Class<T> var2);
  // ...
}
```

**Comment by otcyury** [comment]
Sorry for confusion. Turns out this was an issue with wrong spring-data-r2dbc and I fixed this issue by upgrading to 1.0.0.M2 of this library. I am now getting other compatibility issues with spring-data-r2dbc, but I think I need to contact another team for this.

java.lang.NoSuchMethodError: org.springframework.transaction.reactive.TransactionSynchronizationManager.currentTransaction()Lreactor/core/publisher/Mono;
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.doGetConnection(ConnectionFactoryUtils.java:88) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
