### ISSUE TITLE
IN clause binding

### ISSUE THREAD

**Issue by msoub** [r2dbc/r2dbc-postgresql#224]
#### Current Behavior

```sql
SELECT * FROM users WHERE name IN ($1)
```
when binding the parameter with a list, the following error happens:

<details>
<summary>Cannot encode parameter of type java.util.ArrayList</summary>

```
java.lang.IllegalArgumentException: Cannot encode parameter of type java.util.ArrayList
		at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:142)
		at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:94)
		at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:87)
		at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:45)
		at com.edgelab.recco.pricing.PricingRepository$findAll$1.apply(Pricing.kt:108)
		at com.edgelab.recco.pricing.PricingRepository$findAll$1.apply(Pricing.kt:96)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:156)
```

</details>

#### Expected behavior/code

I'd expect the list to be bound correctly.

**Comment by mp911de** [comment]
This is the expected behavior. Postgres requires a parameter placeholder for each parameter. If you want to bind a collection of parameters, then you must reflect each parameter in your SQL statement and bind each parameter individually:

```sql
SELECT * FROM users WHERE name IN ($1, $2, $3, $n)
```

```java
.bind("$1", firstElement)..bind("$2", secondElement).…
```
