### ISSUE TITLE
Conflict between io.projectreactor.netty and io.projectreactor.ipc

### ISSUE THREAD

**Issue by daelmaak** [r2dbc/r2dbc-postgresql#26]
I am building a small service for which I use spring webflux boot on netty together with r2dbc-postgresql. I am able to start it just alright and when I perform request I get the response back. 

The problem comes up when in request processing an interaction with DB is involved via r2dbc-postgresql. I keep getting initialization errors for class `ReactorNetty.java` from io.projectreactor.netty **after the response was sent** successfully:
`
Caused by: java.lang.IllegalArgumentException: 'PERSISTENT_CHANNEL' is already in use
	at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:113) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.ConstantPool.newInstance(ConstantPool.java:95) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at reactor.netty.ReactorNetty.<clinit>(ReactorNetty.java:614) ~[reactor-netty-0.8.0.RELEASE.jar:0.8.0.RELEASE]
`

The thing is that before ReactorNetty from io.projectreactor.netty (r2dbc-postgresql's dep) tries to be initialized, another `ReactorNetty.java` from project io.projectreactor.ipc (spring webflux boot's dep) already initialized itself. As both classes, while initializing, put the same String values to ConstantPool (mentioned in the stacktrace above) where one value **can't** be put there twice, the initialization fails for the class which came later.
Btw. "spring boot's ReactorNetty" inits itself before response is sent to the client and "r2dbc's ReactorNetty" after the response is sent.

Now as said I get the value out of DB alright and the response as well, it's just that I have a log full of errors and I guess moreover that this is not just cosmetic issue, although I don't see any side effects.

**Deps**
`
compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
compile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
compile "org.springframework.boot:spring-boot-starter-webflux:2.0.6.RELEASE"
compile "io.r2dbc:r2dbc-postgresql:1.0.0.BUILD-SNAPSHOT"
compile "org.springframework.data:spring-data-jdbc:1.0.0.r2dbc-SNAPSHOT"
`

**DB connection**
`
    @Bean
    open fun factory(client: DatabaseClient): R2dbcRepositoryFactory {
        val context = RelationalMappingContext()
        context.afterPropertiesSet()
        return R2dbcRepositoryFactory(client, context)
    }

    @Bean
    open fun databaseClient(factory: ConnectionFactory): DatabaseClient {
        return DatabaseClient.builder().connectionFactory(factory).build()
    }

    @Bean
    open fun connectionFactory(): PostgresqlConnectionFactory {
        val config = PostgresqlConnectionConfiguration.builder()
                .host("localhost")
                .port(5432)
                .database("test")
                .username("postgres")
                .password("example")
                .build()
        return PostgresqlConnectionFactory(config)
    }
`

Repo
`
import org.springframework.data.jdbc.repository.query.Query
import org.springframework.data.repository.reactive.ReactiveCrudRepository
import reactor.core.publisher.Flux

interface UserRepository: ReactiveCrudRepository<Test, Int> {
    @Query("select * from test")
    fun test(): Flux<Test>
}
`

**Comment by violetagg** [comment]
@daelmaak This is fixed with Reactor Netty 0.8.1.RELEASE. Can you try it ?

**Comment by daelmaak** [comment]
You are absolutely right, with 0.8.1 it works!
