### ISSUE TITLE
io.r2dbc.spi.Row.get(Object,Class<T>) fails when r2dbc-postgres is used with Kotlin coroutine.

### ISSUE THREAD

**Issue by mike-neck** [r2dbc/r2dbc-postgresql#91]
`io.r2dbc.spi.Row.get(Object,Class<T>)` fails when r2dbc-postgres is used with Kotlin coroutine.

Versions
---

* r2dbc-postgres : 1.0.0.M7
* Kotlin : 1.3.20
* kotlinx-coroutines-reactor: 1.1.1

Code
---

```kotlin
data class User(val id: Long, val name: String, val created: Instant)

@Test
fun r2dbcWithCoroutine() {
  val options = ConnectionFactoryOptions.builder()
      .option(ConnectionFactoryOptions.DRIVER, "postgresql")
      .option(ConnectionFactoryOptions.HOST, "localhost")
      .option(ConnectionFactoryOptions.PORT, 5432)
      .option(ConnectionFactoryOptions.USER, "postgres-user")
      .option(ConnectionFactoryOptions.PASSWORD, "postgres-pass")
      .option(ConnectionFactoryOptions.DATABASE, "postgres")
      .build()
  val connectionFactory = ConnectionFactories.get(options)
  val user = GlobalScope.mono {
    val conn = connectionFactory.create().awaitSingle()
    val result = conn.createStatement(
        //language=SQL
        "SELECT u.id, u.name, u.created FROM users AS u WHERE u.name = $1")
        .bind("$1", "test-user")
        .execute()
        .awaitSingle()
    return@mono result.map { row, _ -> // 62
      val name = row.get("name", String::class.java) // 63
      val id = row.get("id", Long::class.javaObjectType)
      val created = row.get("created", Instant::class.java)
      if (id != null && name != null && created != null) {
        return@map User(id, name, created)
      } else {
        return@map null
      }
    }.awaitSingle() // 71
  }
  runBlocking {
    println(user.awaitSingle()) // 75
  }
}
```

StackTrace
---

```
java.lang.StringIndexOutOfBoundsException
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:505)
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:796)
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246)
	at io.netty.buffer.AbstractByteBuf.getCharSequence(AbstractByteBuf.java:511)
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.getCharSequence(AbstractUnpooledSlicedByteBuf.java:264)
	at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:516)
	at io.r2dbc.postgresql.util.ByteBufUtils.decode(ByteBufUtils.java:42)
	at io.r2dbc.postgresql.codec.StringCodec.doDecode(StringCodec.java:60)
	at io.r2dbc.postgresql.codec.StringCodec.doDecode(StringCodec.java:34)
	at io.r2dbc.postgresql.codec.AbstractCodec.decode(AbstractCodec.java:64)
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:92)
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1$1.apply(R2Dbc.kt:63)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1$1.apply(R2Dbc.kt:35)
	at io.r2dbc.postgresql.PostgresqlResult.lambda$map$0(PostgresqlResult.java:69)
	at reactor.function.TupleUtils.lambda$function$7(TupleUtils.java:143)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:735)
	at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:78)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:457)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3694)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:112)
	at reactor.core.publisher.MonoRepeatPredicate.subscribe(MonoRepeatPredicate.java:47)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.core.publisher.FluxZip$ZipCoordinator.subscribe(FluxZip.java:579)
	at reactor.core.publisher.FluxZip.handleBoth(FluxZip.java:326)
	at reactor.core.publisher.FluxZip.handleArrayMode(FluxZip.java:267)
	at reactor.core.publisher.FluxZip.subscribe(FluxZip.java:136)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:96)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:94)
	at kotlinx.coroutines.reactive.AwaitKt.awaitSingle(Await.kt:80)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1.invokeSuspend(R2Dbc.kt:71)
	at |b|b|b(Coroutine boundary.|b(|b)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1.invokeSuspend(R2Dbc.kt:62)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$1.invokeSuspend(R2Dbc.kt:75)
Caused by: java.lang.StringIndexOutOfBoundsException: offset 98, count 9, length 0
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:505)
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:796)
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246)
	at io.netty.buffer.AbstractByteBuf.getCharSequence(AbstractByteBuf.java:511)
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.getCharSequence(AbstractUnpooledSlicedByteBuf.java:264)
	at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:516)
	at io.r2dbc.postgresql.util.ByteBufUtils.decode(ByteBufUtils.java:42)
	at io.r2dbc.postgresql.codec.StringCodec.doDecode(StringCodec.java:60)
	at io.r2dbc.postgresql.codec.StringCodec.doDecode(StringCodec.java:34)
	at io.r2dbc.postgresql.codec.AbstractCodec.decode(AbstractCodec.java:64)
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:92)
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1$1.apply(R2Dbc.kt:63)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1$1.apply(R2Dbc.kt:35)
	at io.r2dbc.postgresql.PostgresqlResult.lambda$map$0(PostgresqlResult.java:69)
	at reactor.function.TupleUtils.lambda$function$7(TupleUtils.java:143)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:735)
	at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:78)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:457)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3694)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:112)
	at reactor.core.publisher.MonoRepeatPredicate.subscribe(MonoRepeatPredicate.java:47)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.core.publisher.FluxZip$ZipCoordinator.subscribe(FluxZip.java:579)
	at reactor.core.publisher.FluxZip.handleBoth(FluxZip.java:326)
	at reactor.core.publisher.FluxZip.handleArrayMode(FluxZip.java:267)
	at reactor.core.publisher.FluxZip.subscribe(FluxZip.java:136)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:96)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:94)
	at kotlinx.coroutines.reactive.AwaitKt.awaitSingle(Await.kt:80)
	at com.example.db.R2Dbc$r2dbcWithCoroutine$user$1.invokeSuspend(R2Dbc.kt:71)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

Before `io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:796)` is called, `ByteBuf`'s `readableBytes()` returns `9`. But `ByteBuf` returns `0` after entering `io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:796)` .

**Comment by mp911de** [comment]
That's fixed now via #116.
